---
- name: Setup ospf
  hosts: r1
  become: yes
  
  vars:
    router_name: 'r1'
    eth1_cost: '10'
    eth2_cost: '10'
    router_area: '0.0.0.1'
    A0net1: '12.0.0.0/30'
    A0net2: '14.0.0.0/30'
    router_lan: '11.10.0.0/24'

    
  tasks:
    - name: Add epel-release repo
      yum:
        name: epel-release
        state: present
        
    - name: disable ssl for repo epel
      lineinfile: 
        dest: /etc/yum.repos.d/epel.repo
        insertafter: 'enabled=1'
        line: 'sslverify=0'

    - name: Add quagga
      yum:
        name: quagga
        state: present
        
    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      selinux:
        policy: targeted
        state: permissive

    - name: edit sysctl ip_forward
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes

    - name: edit sysctl rp_filter
      sysctl:
        name: net.ipv4.conf.all.rp_filter
        value: '0'
        sysctl_set: yes
        state: present
        reload: yes
        
    - name: Manage zebra conf
      template:
        src: templates/zebra.conf.j2
        dest: /etc/quagga/zebra.conf
        owner: root
        group: root
        mode: 0644
      notify: restart zebra

    - name: Manage ospfd conf
      template:
        src: templates/ospfd.conf.j2
        dest: /etc/quagga/ospfd.conf
        owner: root
        group: root
        mode: 0644
      notify: restart ospfd
      
    - name: daemon started
      systemd:
        name: zebra
        state: started
        enabled: yes

       
    - name: demon started
      systemd:
        name: ospfd
        state: started
        enabled: yes
        
  handlers:
  - name: restart zebra
    service:
      name: zebra
      state: restarted
  - name: restart ospfd
    service:
      name: ospfd
      state: restarted
